### ISSUE TITLE
Why does PUSH create an Object instead of an Array

### ISSUE THREAD

**Issue by jhnsntmthy** [oscardelben/firebase-ruby#14]
the PUSH in the FirebaseJS library creates an array object and pushes onto that. Why doesn't the Ruby -REST API do the same, it rather creates an object, that I cannot run filters on in Angular.

**Comment by vincentwoo** [comment]
Firebase by default creates objects, and arrays in Firebase are just objects with numeric keys. Closing this issue. @crazy2be's solution for converting in userland should work fine.
