### ISSUE TITLE
Could not parse auth token

### ISSUE THREAD

**Issue by newtriks** [oscardelben/firebase-ruby#23]
Since upgrading to the latest version i.e. 0.2 from 0.1 all requests fail with the following error `Could not parse auth token`. 

To confirm, all requests previously worked and the data has security access open to all read/write on my example.

Is there an additional auth related step I potentially am missing?

**Comment by hugohow** [comment]
I have the same problem now :/ It's maybe due to some upgrades of Firebase

**Comment by hugohow** [comment]
No it's ok, I put the wrong key for secret_key.

**Comment by jakehockey10** [comment]
I'm having this issue still and I'm using Firebase to copy the key.  To clarify, I created a user account with an email and password and I'm copying the UID.  Is this correct?

**Comment by arcticleo** [comment]
@jakehockey10 No, you use the secret key, which you can find under application settings. Application settings can be found by clicking the cog at the top of the left project navigation.

**Comment by jakehockey10** [comment]
@arcticleo Sorry if this seems silly.  I clicked on the cog towards the top left and couldn't find anything other than a Web API Key.  I tried it with that and still didn't have any luck.

**Comment by jakehockey10** [comment]
Found the answer here if anyone needs to know: http://stackoverflow.com/questions/37418372/firebase-where-is-my-account-secret-in-the-new-console/37418932#37418932
