### ISSUE TITLE
Bypassing security rules

### ISSUE THREAD

**Issue by Eckho28** [oscardelben/firebase-ruby#28]
Does inputting your Firebase secret here allow your server to bypass any security rules that have been set?:

firebase = Firebase::Client.new(base_uri, secret_key)

**Comment by vincentwoo** [comment]
Yes, if the secret key that you use is an admin key. It is possible to use an authentication token with weaker privileges as well: https://www.firebase.com/docs/rest/api/#section-query-parameters
