### ISSUE TITLE
Global @firebase

### ISSUE THREAD

**Issue by tejasmanohar** [oscardelben/firebase-ruby#29]
How do I use firebase across methods and not locally as shown in the examples? @firebase, see paste...
http://bpaste.net/show/501b6a67c8d4

**Comment by vincentwoo** [comment]
The ruby firebase client requires that you make a client instance object to query against your firebase db. Can you update your code snippet to show your example inline or in a gist? It 404s for me.

**Comment by tejasmanohar** [comment]
I got it covered.

**Comment by holgersindbaek** [comment]
@tejasmanohar @vincentwoo How did you end up doing this? I ended up having this in my initializer firebase.rb:

    $firebase ||= Firebase::Client.new("https://app.firebaseio.com", ENV["FIREBASE_SECRET_KEY"])

Is this how you're doing it as well?

**Comment by tejasmanohar** [comment]
@holgersindbaek Tbh, I don't have copies of the code anymore & can't remember what I did (or why / what I was even using Firebase for haha). I think it's best you open another issue if you're facing a problem on this. That said, what you've done looks fair :)

**Comment by vincentwoo** [comment]
@holgersindbaek pretty much yes, but personally i opt for constant naming:

```ruby
FIREBASE = Firebase::Client...
```
