### ISSUE TITLE
Could not open library 'libcurl'

### ISSUE THREAD

**Issue by pacey** [oscardelben/firebase-ruby#31]
I followed the instructions on the readme bit I get the following error when I try and run the ruby application:

 (LoadError)ib/ruby/gems/1.9.1/gems/ffi-1.9.6-x86-mingw32/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.6-x86-mingw32/lib/ffi/library.rb:100:in `map'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.6-x86-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curls/settings.rb:6:in `<module:Curl>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curls/settings.rb:1:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curl.rb:27:in `<module:Curl>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curl.rb:13:in `<module:Ethon>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon/curl.rb:8:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ethon-0.7.1/lib/ethon.rb:11:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/firebase-0.2.2/lib/firebase/request.rb:1:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/firebase-0.2.2/lib/firebase.rb:4:in `<class:Client>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/firebase-0.2.2/lib/firebase.rb:2:in `<module:Firebase>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/firebase-0.2.2/lib/firebase.rb:1:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from D:/sandboxes/odin-dashboard/jobs/beer_run.rb:1:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39:in `require'
        from D:/sandboxes/odin-dashboard/config.ru:1:in `block in <main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from D:/sandboxes/odin-dashboard/config.ru:in `new'
        from D:/sandboxes/odin-dashboard/config.ru:in `<main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
        from C:/Ruby193/bin/rackup:23:in `load'
        from C:/Ruby193/bin/rackup:23:in `<main>'

It looks like the ffi library was a dependency of this firebase gem.

**Comment by vincentwoo** [comment]
We're switching to `HTTPClient` instead of depending on a libcurl wrapper. Stand by!

**Comment by Halimov94** [comment]
Help me please i see this massage : could not open library 'libcurl.dll | after open ruby script how solve this

**Comment by nnvnaveen** [comment]
Hi, I am facing the same issue in windows machine. any resolution

**Comment by alidhillon** [comment]
I was able to fix things by running sudo apt-get install libcurl3 which installed curl again and made things work
