### ISSUE TITLE
Listen for changes

### ISSUE THREAD

**Issue by holgersindbaek** [oscardelben/firebase-ruby#38]
Is there any way you can listen for changes made in your Firebase database with this gem? So when a new user signs up using their iPhone and that user gets saved in the database, then the I would now it in my Ruby app using this gem?

**Comment by vincentwoo** [comment]
`firebase-ruby` just interacts with the Firebase REST API - it doesn't do real-time, which is hard to do in a fairly synchronous language like Ruby. Such a feature is probably out of scope for this gem.
