### ISSUE TITLE
Firing event takes ~2 seconds

### ISSUE THREAD

**Issue by swatisinghi** [oscardelben/firebase-ruby#42]
I am using firebase 0.2.2. Although things are working, the time between push and child-added operations take 2 seconds. This is not realtime right?

I am using firebase 0.2.2 because of this https://github.com/oscardelben/firebase-ruby/issues/41

```
[DEBUG pid: 10145: 15-05-08 17:42:40  ] ETHON: Libcurl initialized
[DEBUG pid: 10145: 15-05-08 17:42:40  ] ETHON: started MULTI
[DEBUG pid: 10145: 15-05-08 17:42:42  ] ETHON:         performed EASY effective_url=https://xxxxxxxxx.firebaseio.com/xxxx/xxxxx.json response_code=200 total_time=1.483105 return_code=ok
[DEBUG pid: 10145: 15-05-08 17:42:42  ] ETHON: performed MULTI
```

**Comment by vincentwoo** [comment]
HTTPClient is probably going to be more performant. Any chance you can submit a PR to to make the gem backwards compatible with 1.8.7?

Keep in mind also that firebase-ruby works over the HTTP API, not the real-time streaming socket API that the JS client uses.
