### ISSUE TITLE
HttpClient should use timeouts

### ISSUE THREAD

**Issue by bbansal** [oscardelben/firebase-ruby#45]
The HTTPClient library default timeout is not set and it keeps on waiting forever when network issues happen. please add a timeout parameter which can be passed down 

https://github.com/oscardelben/firebase-ruby/blob/master/lib/firebase/request.rb#L7

**Comment by vincentwoo** [comment]
Can you contribute a PR that does just that?

**Comment by bbansal** [comment]
https://github.com/oscardelben/firebase-ruby/pull/46

**Comment by vincentwoo** [comment]
done in `0.2.5`
