### ISSUE TITLE
Cut a new gem version?

### ISSUE THREAD

**Issue by vincentwoo** [oscardelben/firebase-ruby#49]
@oscardelben, I made some fairly serious changes, and exposed the underlying HTTP client. I think it warrants a gem cut, as people are asking for the ability to set timeout values.

**Comment by vincentwoo** [comment]
Relevant commits: https://github.com/oscardelben/firebase-ruby/commit/138b1e1461ff33da506b0d7992b42e3544be9cf1 and https://github.com/oscardelben/firebase-ruby/commit/8cb61f70392968c4b6ac0d3f5ce124a98c1e131b

**Comment by vincentwoo** [comment]
@oscardelben I'm also happy to admin the rubygems bit too, if you want another pair of hands there.

**Comment by oscardelben** [comment]
New version pushed!
