### ISSUE TITLE
Timeout when using Set on Heroku Cedar-14

### ISSUE THREAD

**Issue by Eckho28** [oscardelben/firebase-ruby#50]
Hi, I'm currently getting sporadic timeouts when trying to use Firebase.set from either a controller or model. Pushes seem to be fine however for some reason. Everything was working perfectly on Cedar-10. Anyone else experience this?

**Comment by vincentwoo** [comment]
Some calls are going to be more expensive, and sometimes Firebase just can't keep up, and they'll drop a call. You can try playing with the timeout values as described in the README, but definitely some calls are going to fail. If you can reproduce more systemically or in a way that doesn't just look like Firebase failure, please feel free to reopen.

**Comment by Eckho28** [comment]
The thing is that all the Javascript API calls are working perfectly, and the same method was working without a single timeout for over 10 months in production, until Heroku upgraded their architecture, so I'm pretty sure something about Cedar-14 broke something in this gem. I ended up just removing it altogether and going with another solution.
