### ISSUE TITLE
How to get number of Children?

### ISSUE THREAD

**Issue by Brotakuu** [oscardelben/firebase-ruby#53]
How can I call the `.numChildren()` method

      base_uri = 'https://demo.firebaseio.com/demo/
      firebase = Firebase::Client.new(base_uri)
      @currentVisitors = firebase.get("currentVisitors")

I'd like to return the number of children in `currentVisitors` which is nested in `firebaseio.com/demo/currentVisitors`

**Comment by vincentwoo** [comment]
Firebase unfortunately doesn't have an endpoint to return the number of children of a node. You can read about what is supported here: https://www.firebase.com/docs/rest/api/

Keep in mind the ruby client uses the REST api and not the realtime Javascript API.
