### ISSUE TITLE
😋Add support for multi-location updates 

### ISSUE THREAD

**Issue by mklb** [oscardelben/firebase-ruby#54]
Firebase added the ability to make multi location updates with one request. This would be awesome! 

The blog post: https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html

**Comment by vincentwoo** [comment]
@mikelehen, this would be cool to add to `firebase-ruby`.

Unfortunately https://www.firebase.com/docs/rest/api/#section-patch doesn't seem to give any guidance on what the REST call should look like for a deep path update. Can you let us know slash update that page?

**Comment by mikelehen** [comment]
It works the same as in the realtime API, e.g.:

```
curl -X PATCH -d '{"foo/bar":"test", "baz/quu": 42}' https://mike.firebaseio-demo.com/.json
```

I'll log a bug to get the REST docs updated.

**Comment by vincentwoo** [comment]
@mklb just to follow up literally a year later: you can do this already in `firebase-ruby`:

`firebase_ref.update('', { "test/blah" => 11, "test2/foo" => 12 })`
