### ISSUE TITLE
Getting Exception *** URI::InvalidURIError Exception: bad URI(is not URI?)

### ISSUE THREAD

**Issue by YSTomar** [oscardelben/firebase-ruby#55]
Hi,

I am try to initialize Firebase instance but I am getting below exception everytime

*** URI::InvalidURIError Exception: bad URI(is not URI?): {:base_url=>"https://myfirebaseapp.firebaseio.com/", :default_header=>{"Content-Type"=>"application/json"}}

Please suggest me some way how can I move out with this API

**Comment by vincentwoo** [comment]
What version of `firebase-ruby` are you using? Can you show us the code you use to try to initialize your firebase instance?

**Comment by YSTomar** [comment]
Hi VIncentwoo,

I got the issue, Actually my Gemfile used older version of httpclient(2.4.1), and that version have issue.

I have defined  httpclient's gem  latest version into the Gemfile before firebase and now everything working fine

Below is declaration of gems in my Gemfile

gem 'httpclient', '~> 2.7.1'

gem 'firebase', '~> 0.2.6'
