### ISSUE TITLE
Random connection problems

### ISSUE THREAD

**Issue by holgersindbaek** [oscardelben/firebase-ruby#56]
I'm running the firebase-ruby gem on Rails, which is running on Heroku. I initialize a global instance like so - https://github.com/oscardelben/firebase-ruby/issues/29 - but after some time I get this error when I try to update or set something on Firebase:

    Errno::ECONNRESET (Connection reset by peer - SSL_connect): 
      app/controllers/v1/user_controller.rb:39:in `update_email' 

And this is the code that fails:

    $firebase.update("users/#{@user_id}", { email: @email, email_verified: nil })

What could be the issue here?

**Comment by holgersindbaek** [comment]
And here's the full error log: https://gist.github.com/holgersindbaek/2b4a021aba1f6a8724eb

Any guesses on what it might be?

**Comment by vincentwoo** [comment]
Firebase goes down sometimes and some percentage of requests fail as a matter of course. Are you seeing these at a very high frequency?

**Comment by holgersindbaek** [comment]
I'm seeing this a couple of times a day. I don't know if that is what you'd call a high frequency?

**Comment by holgersindbaek** [comment]
Not getting these anymore either.
