### ISSUE TITLE
Planned support for realtime client?

### ISSUE THREAD

**Issue by sksea** [oscardelben/firebase-ruby#60]
Hi, wanted to use firebase for my rails project -- I saw https://github.com/oscardelben/firebase-ruby/issues/53 and it seems many features on google's firebase docs lack support from this client. Something trivial like incrementing a counter in the database requires multiple http requests? Any idea if an official ruby sdk is in the works?

**Comment by vincentwoo** [comment]
Async programming isn't something plays very well in the Ruby paradigm. In so much as there *is* a ruby client, this is the official one.
