### ISSUE TITLE
Upload image / media

### ISSUE THREAD

**Issue by syedali90** [oscardelben/firebase-ruby#61]
I don't see any support for image/media upload in gem docs.. neither in firebase rest API docs ..
is there any way i can achieve that ? upload media to firebase storage ?

**Comment by vincentwoo** [comment]
Firebase has a lot of product offerings now, but this gem only touches the realtime storage database, which is basically a giant JSON store. For static media check out firebase's hosting product: https://www.firebase.com/docs/hosting/
