### ISSUE TITLE
Leading slash on path ignores base_uri reference

### ISSUE THREAD

**Issue by ptolemybarnes** [oscardelben/firebase-ruby#63]
For example,

```ruby
# DELETE
parent_ref = Firebase::Client.new('https://my-firebase-db.firebaseio.com/parent')
parent_ref.delete('/child')
```

... this will make a delete request to 'https://my-firebase-db.firebaseio.com/child', rather than 'https://my-firebase-db.firebaseio.com/parent/child'. This is because of the way the Addressable gem, used by httpclient, concatenates a base url with a path.

Is this what is intended? I found it quite surprising.

**Comment by vincentwoo** [comment]
I think of the ambiguous behavior invited by allowing `/child` as a reference, the httpclient behavior is the least surprising. I think the firebase  (and firebase-ruby's) docs are careful not to use absolute path child refs.

**Comment by ptolemybarnes** [comment]
@vincentwoo Sorry, not quite sure what you mean. 🤔 

My perspective is that once I've got a reference to, `/foo`, it's nice to be able to make any requests I like against that reference and not have to worry that I might accidentally delete data outside of the scope of that reference.

**Comment by ptolemybarnes** [comment]
hey @vincentwoo any thoughts on ^^? I'm happy to submit a PR, or close this issue.

**Comment by vincentwoo** [comment]
I would take a pr that emits an error when you try to use child with a nonrelative path. Thoughts?

**Comment by ptolemybarnes** [comment]
I like. Though why raise an error rather than implicitly convert to a relative path? I don't have much experience with API design so I'm curious.

**Comment by vincentwoo** [comment]
We should avoid silent surprising behavior. Since our instincts about what would happen with an absolute path were completely different, I think it should emit an error rather than silently do the thing half the people are expecting and the opposite of what the other half are expecting.

**Comment by ptolemybarnes** [comment]
Okay, that's what I thought! Thanks for clarifying.
