### ISSUE TITLE
Upgrade from firebase

### ISSUE THREAD

**Issue by hugohow** [oscardelben/firebase-ruby#64]
Hello,

It seems that Firebase has upgraded the way to initialize a firebase client 

https://firebase.google.com/docs/admin/setup

We have to import a json file generated by Firebase, instead of tap a secret key.
Any upgrade planned for firebase-ruby to adapt with this ?

Thanks for this library !

**Comment by gugakatsi** [comment]
you can still use the library pretty well, and you can get secret key too , but ye  ,you kinda right in some point

**Comment by pothibo** [comment]
I've forked this repo and made it work on one of my project, I'm planning to eventually do a PR when I have the time, but feel free to check it out!

https://github.com/crossfield/firebase-ruby

**Comment by gugakatsi** [comment]
@pothibo can you checkout my issue over there? i hope you can help me.

**Comment by dkoprov** [comment]
@pothibo I hope you'll have a free time in a nearest future to make a Pull Request since it's really needed feature and I plan to integrate an adapter to firebase for ActionCable in rails.
Thank you in advance!

**Comment by praveensah** [comment]
Has this been merged?

**Comment by LivioGama** [comment]
It looks like from now, using the gem without this fix make the server acts like it was unauthenticated. So if you have rules on your database, you might not be able to right everywhere https://firebase.google.com/docs/database/admin/start

**Comment by vincentwoo** [comment]
I don't have a lot of time to look into this (as we are still using the legacy Auth method against mostly public Firebase data) but would happily review a PR for this!

**Comment by pothibo** [comment]
I'm not using Firebase anymore, but I can look at creating a base PR so I can get the ball rolling and someone else can add commit to it if more work is needed. I'll check it later today
