### ISSUE TITLE
Gem install throws error. 

### ISSUE THREAD

**Issue by srideviaishwariya** [oscardelben/firebase-ruby#67]
$ gem install firebase
ERROR:  Could not find a valid gem 'firebase' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)
$ gem 'firebase', '~> 0.2.6'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command firebase,

**Comment by vincentwoo** [comment]
This is a problem with your connectivity to rubygems.org and not with this particular gem.
