### ISSUE TITLE
Permission denied to firebase

### ISSUE THREAD

**Issue by mk-nyein** [oscardelben/firebase-ruby#69]
base_uri = 'https://fir-api-test1.firebaseio.com/'
    firebase = Firebase::Client.new(base_uri)
    response = firebase.push("articles", { :title => 'Pick the milk', :content => 1 })
    puts "===#{response.success?}==="
    puts "===#{response.code }==="
    puts "===#{response.body}==="
    puts "===#{response.raw_body}==="

in console

    ===false===
    ===401===
    ==={"error"=>"Permission denied"}===
    ==={
      "error" : "Permission denied"
    }
    ===

**Comment by vincentwoo** [comment]
You may be using security rules that prevent this or have the wrong repo name.
