### ISSUE TITLE
Setting Key on Push

### ISSUE THREAD

**Issue by garyfoster** [oscardelben/firebase-ruby#71]
Is it possible to provide a key when pushing data without Firebase generating it's own?

**Comment by arcticleo** [comment]
When you use update instead of push, it doesn't add its own key.

**Comment by gugakatsi** [comment]
@garyfoster can you gave us an example? question little bit confused me.

**Comment by garyfoster** [comment]
Sorry, the answer from @arcticleo solved my problem, closing. Thanks all!
