### ISSUE TITLE
get(path, query_options) ignoring query options

### ISSUE THREAD

**Issue by beckah** [oscardelben/firebase-ruby#73]
My firebase data looks like the following:
```
"receipts" : {
    "123abc123" : {
      "receiptid" : "fdsjfkdasfk4444r3",
      "storeid" : "123abc",
      "storename" : "Anita's Cheetahs",
      "timestampcreated" :  1487514076000,
      "total" : 9.99,
      "userid" : "45YBt78mEUOSKaHuCuuTi6IBFq02"
    },
    "1487458237544842829" : {
      "receiptid" : "1487458237544842829",
      "storeid" : "123abc",
      "storename" : "moe's grocery",
      "timestampcreated" :  1487514076000,
      "total" : 0.99,
      "userid" : "yXYZa"
    }
}
```

I trying to retrieve all receipts with a `userid` equal to "yXYZa".

My ruby code looks like the following:
```
base_uri = 'https://scanhappy-3e9e2.firebaseio.com/'
secret_key = "RMI15TkVVPASxUcm2WqyCsZgruZlWaISEijEXx52"
firebase = Firebase::Client.new(base_uri, secret_key)
response = firebase.get("receipts",  {"userid" => "yXYZa"})
```

However, the response I'm getting is returning every object in `receipts`.

Is my data too nested (ie. a unique ID for each object) for firebase-rails get method to work?

**Comment by vincentwoo** [comment]
I do not believe that is a real query format that Firebase REST supports. Please see https://firebase.google.com/docs/reference/rest/database/

**Comment by beckah** [comment]
@vincentwoo it does, at least for both android and web. typically, it will be specified by something like the following:
`reference.child("receipts").orderBy("userid").equalTo("yXYZa")`
https://firebase.google.com/docs/reference/rest/database/#section-param-query

**Comment by vincentwoo** [comment]
Right, you have to specify the params `equalTo` and so forth. We can't intuit what the hash `userid => str` means without context. You can see the spec for an example https://github.com/oscardelben/firebase-ruby/blob/master/spec/firebase_spec.rb#L44
