### ISSUE TITLE
:priority or :".priority" ?

### ISSUE THREAD

**Issue by THUFIR** [oscardelben/firebase-ruby#79]
really, it's in the link:

https://stackoverflow.com/q/23527824/262852

> 
> up vote         1         down vote | The solution is to use the priority field in firebase, however, the  documentation for the Ruby wrapper is incorrect. The docs suggest using   response = firebase.push("todos", { :name => 'Pick the milk', :priority => 1 })  The priority field is actually '.priority' and it's expecting a symbol so you'll need to use something like this instead:  response = firebase.push("todos", { :name => 'Pick the milk', :".priority" => 1 }) |  
> -- | -- | --
>

**Comment by vincentwoo** [comment]
Thanks for the report!
