### ISSUE TITLE
Firebase created a new authentication

### ISSUE THREAD

**Issue by thiagopnobre** [oscardelben/firebase-ruby#80]
The problem here is that the old databasesecret link (https://console.firebase.google.com/project/[projectname]/settings/serviceaccounts/databasesecrets) is now deprecated. The new key is on the settings and it's not the same of the previous databasesecret. So, when I tried to use the new key, I wasn't able to authenticate.

**Comment by rflorence** [comment]
See #64. The https://github.com/crossfield/firebase-ruby fork uses the new Firebase authentication, but it hasn't been merged here.

**Comment by vincentwoo** [comment]
Would love to take a PR around this!
